const SUPABASE_URL='https://lzzujiyiltwfrvcwnrlh.supabase.co';
const SUPABASE_KEY='sb_publishable_Ui-w7uI27X5dEybtGozMTA_kuFyfM2R';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s);let prompts=[],activeCat='All',currentUser=null,currentProfile=null,editingId=null,editingImage='';
const money=v=>'$'+Number(v||0).toFixed(2);const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function isAdmin(){return currentProfile?.role==='admin'}
async function loadPrompts(){const {data,error}=await sb.from('prompts').select('id,title,category,description,prompt_text,sort_order,published,image_url,price,duration,created_at').order('sort_order',{ascending:true}).order('created_at',{ascending:false});if(error){$('#grid').innerHTML='<div class="empty">Could not load prompts.</div>';return}prompts=data||[];renderPrompts();if(isAdmin())renderAdminList()}
function renderPrompts(){const q=$('#search').value.trim().toLowerCase();const list=prompts.filter(p=>(activeCat==='All'||p.category===activeCat)&&(!q||(`${p.title} ${p.category} ${p.description} ${p.prompt_text}`).toLowerCase().includes(q)));$('#grid').innerHTML=list.length?list.map(p=>`<article class="card"><div class="thumb" style="${p.image_url?`background-image:url('${esc(p.image_url)}')`:''}"><span class="badge">${esc(p.category)}</span><span class="dur">${esc(p.duration||'10s')}</span></div><div class="body"><h3>${esc(p.title)}</h3><div class="desc">${esc(p.description||'Premium PromptStudio prompt')}</div><div class="pricebar"><span class="price">${money(p.price)}</span><button class="buy viewPrompt" data-id="${p.id}">View Prompt</button></div></div></article>`).join(''):'<div class="empty">No prompts found.</div>';document.querySelectorAll('.viewPrompt').forEach(b=>b.onclick=()=>openPrompt(b.dataset.id))}
function openPrompt(id){const p=prompts.find(x=>x.id===id);if(!p)return;$('#modalTitle').textContent=p.title;$('#modalMeta').textContent=`${p.category} • ${p.duration||'10s'}`;$('#modalPrompt').textContent=p.prompt_text;$('#modalPrice').textContent=money(p.price);$('#promptModal').classList.add('open')}
async function refreshAuth(){const {data:{session}}=await sb.auth.getSession();currentUser=session?.user||null;currentProfile=null;if(currentUser){const {data}=await sb.from('profiles').select('full_name,role').eq('user_id',currentUser.id).maybeSingle();currentProfile=data||null}updateAuthUI();await loadPrompts()}
function updateAuthUI(){const signed=!!currentUser;$('#loginBtn').style.display=signed?'none':'';$('#signupBtn').style.display=signed?'none':'';$('#logoutBtn').style.display=signed?'':'none';$('#accountLabel').style.display=signed?'inline':'none';$('#accountLabel').textContent=signed?(currentProfile?.full_name||currentUser.email):'';$('#adminToggle').style.display=isAdmin()?'inline-flex':'none';if(!isAdmin())$('#adminSection').classList.remove('open')}
function openAuth(mode){authMode=mode;$('#authModal').classList.add('open');setAuthMode(mode)}let authMode='login';
function setAuthMode(mode){authMode=mode;$('#loginTab').classList.toggle('active',mode==='login');$('#signupTab').classList.toggle('active',mode==='signup');$('#nameField').style.display=mode==='signup'?'grid':'none';$('#authSubmit').textContent=mode==='login'?'Login':'Create Account';$('#authStatus').textContent=''}
async function submitAuth(){const email=$('#authEmail').value.trim(),password=$('#authPassword').value,name=$('#authName').value.trim();$('#authStatus').textContent='Working...';let res;if(authMode==='login')res=await sb.auth.signInWithPassword({email,password});else res=await sb.auth.signUp({email,password,options:{data:{full_name:name}}});if(res.error){$('#authStatus').textContent=res.error.message;return}$('#authStatus').textContent=authMode==='signup'&&!res.data.session?'Account created. Check your email if confirmation is required.':'Success.';if(res.data.session){$('#authModal').classList.remove('open');await refreshAuth()}}
function renderAdminList(){if(!isAdmin())return;$('#adminList').innerHTML=prompts.length?prompts.map(p=>`<div class="adminRow"><div class="adminPic" style="${p.image_url?`background-image:url('${esc(p.image_url)}')`:''}"></div><div><b>${esc(p.title)}</b><small>${esc(p.category)} • ${money(p.price)} • ${p.published?'Published':'Draft'}</small></div><div class="rowBtns"><button class="edit" data-edit="${p.id}">Edit</button><button class="del" data-del="${p.id}">Delete</button></div></div>`).join(''):'<div class="status">No prompts yet.</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>startEdit(b.dataset.edit));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deletePrompt(b.dataset.del))}
function resetForm(){editingId=null;editingImage='';$('#formHeading').textContent='Upload New Prompt';$('#savePrompt').textContent='Publish Prompt';['titleInput','categoryInput','descriptionInput','promptInput'].forEach(id=>$('#'+id).value='');$('#priceInput').value='2.99';$('#durationInput').value='10s';$('#imageInput').value='';$('#imagePreview').style.backgroundImage='';$('#imagePreview').textContent='Choose an image';$('#adminStatus').textContent=''}
function startEdit(id){if(!isAdmin())return;const p=prompts.find(x=>x.id===id);if(!p)return;editingId=id;editingImage=p.image_url||'';$('#formHeading').textContent='Edit Prompt';$('#savePrompt').textContent='Save Changes';$('#titleInput').value=p.title||'';$('#categoryInput').value=p.category||'';$('#descriptionInput').value=p.description||'';$('#promptInput').value=p.prompt_text||'';$('#priceInput').value=p.price||0;$('#durationInput').value=p.duration||'10s';$('#imagePreview').textContent='';$('#imagePreview').style.backgroundImage=p.image_url?`url('${p.image_url}')`:'';location.hash='#adminSection'}
async function uploadImage(file){const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-');const path=`${currentUser.id}/${Date.now()}-${safe}`;const {error}=await sb.storage.from('prompt-images').upload(path,file,{upsert:false});if(error)throw error;return sb.storage.from('prompt-images').getPublicUrl(path).data.publicUrl}
async function savePrompt(){if(!isAdmin()){$('#adminStatus').textContent='Admin permission required.';return}const title=$('#titleInput').value.trim(),category=$('#categoryInput').value.trim(),prompt=$('#promptInput').value.trim();if(!title||!category||!prompt){$('#adminStatus').textContent='Title, category and full prompt are required.';return}$('#adminStatus').textContent='Saving...';try{let image=editingImage;const file=$('#imageInput').files[0];if(file)image=await uploadImage(file);const payload={title,category,description:$('#descriptionInput').value.trim(),prompt_text:prompt,image_url:image||'',price:Number($('#priceInput').value||0),duration:$('#durationInput').value.trim()||'10s',published:true};const result=editingId?await sb.from('prompts').update(payload).eq('id',editingId):await sb.from('prompts').insert(payload);if(result.error)throw result.error;$('#adminStatus').textContent='Saved successfully.';resetForm();await loadPrompts()}catch(e){$('#adminStatus').textContent=e.message||'Could not save prompt.'}}
async function deletePrompt(id){if(!isAdmin())return;if(!confirm('Delete this prompt?'))return;const {error}=await sb.from('prompts').delete().eq('id',id);if(error){alert(error.message);return}await loadPrompts()}
$('#searchBtn').onclick=renderPrompts;$('#search').addEventListener('input',renderPrompts);document.querySelectorAll('.cat').forEach(b=>b.onclick=()=>{activeCat=b.dataset.cat;document.querySelectorAll('.cat').forEach(x=>x.classList.toggle('active',x===b));renderPrompts()});document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{activeCat=b.dataset.cat;document.querySelectorAll('.cat').forEach(x=>x.classList.toggle('active',x.dataset.cat===activeCat));location.hash='#prompts';renderPrompts()});
$('#loginBtn').onclick=()=>openAuth('login');$('#signupBtn').onclick=()=>openAuth('signup');$('#loginTab').onclick=()=>setAuthMode('login');$('#signupTab').onclick=()=>setAuthMode('signup');$('#authSubmit').onclick=submitAuth;$('#closeAuth').onclick=()=>$('#authModal').classList.remove('open');$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();await refreshAuth()};$('#adminToggle').onclick=()=>{if(isAdmin()){$('#adminSection').classList.add('open');location.hash='#adminSection';renderAdminList()}};$('#closeAdmin').onclick=()=>$('#adminSection').classList.remove('open');$('#savePrompt').onclick=savePrompt;$('#resetForm').onclick=resetForm;$('#imageInput').onchange=e=>{const f=e.target.files[0];if(!f)return;$('#imagePreview').textContent='';$('#imagePreview').style.backgroundImage=`url('${URL.createObjectURL(f)}')`};$('#closePrompt').onclick=()=>$('#promptModal').classList.remove('open');$('#promptModal').onclick=e=>{if(e.target.id==='promptModal')$('#promptModal').classList.remove('open')};$('#authModal').onclick=e=>{if(e.target.id==='authModal')$('#authModal').classList.remove('open')};sb.auth.onAuthStateChange(()=>setTimeout(refreshAuth,0));refreshAuth();
