(function(){
  const dictionaries={
    en:{
      'brand.subtitle':'Video Prompt Marketplace','nav.home':'Home','nav.browse':'Browse Prompts','nav.explore':'Explore Marketplace','nav.admin':'Admin Panel','nav.login':'Login','nav.signup':'Sign Up','nav.logout':'Logout',
      'home.badge':'★ PREMIUM VIDEO PROMPTS','home.titleA':'Create Stunning','home.titleB':'Videos. Faster.','home.desc':'Discover and buy high-quality AI video prompts for any style, mood, or platform. Start with stronger ideas and create polished videos without beginning from zero.','home.explore':'Explore Marketplace →','home.new':'Browse New Prompts','home.premium':'Premium Quality','home.premiumSub':'Carefully curated prompts','home.save':'Save Time','home.saveSub':'Create faster with ready ideas','home.creators':'For All Creators','home.creatorsSub':'Built for every video style','home.likes':'Community Likes','home.views':'Marketplace Views','home.buyers':'Happy Buyers','home.made':'MADE FOR CREATORS','home.showTitle':'Everything you need to turn an idea into a stronger video.','home.showDesc':'PromptStudio focuses on clean, useful prompt products—not clutter. Browse visual examples, compare prices, and open the full prompt before buying.','home.move':'Move faster','home.moveDesc':'Skip the blank page and start from a structured prompt designed for video generation.','home.presentation':'Premium presentation','home.presentationDesc':'Every listing includes a visual cover, clear title, category, duration, description, and price.','home.easy':'Easy marketplace','home.easyDesc':'Browse the store in a separate clean page while Admin controls remain protected in the backend.','home.marketKicker':'PROMPT MARKETPLACE','home.marketTitle':'A clean store for premium prompt products.','home.marketDesc':'Browse products with large visual previews, clear pricing, and a focused shopping experience.','home.openBrowse':'Open Browse Prompts','home.ready':'READY TO CREATE?','home.finalTitle':'Find your next video prompt today.','home.finalDesc':'Open the marketplace and choose a prompt that fits your next project.','home.browseArrow':'Browse Prompts →','home.footer':'© 2026 PromptStudio — Premium Video Prompt Marketplace',
      'market.badge':'✦ PROMPTSTUDIO MARKETPLACE','market.titleA':'Shop premium','market.titleB':'video prompts','market.titleC':'for your next creation.','market.desc':'Explore admin-curated prompt products with visual covers, clear pricing, and ready-to-use creative direction.','market.searchPlaceholder':'Search prompts by title, style, or keyword...','market.search':'Search','market.adminCurated':'Admin Curated','market.adminCuratedSub':'Only approved prompts are published','market.visualListings':'Visual Listings','market.visualListingsSub':'Cover image, title and details','market.clearPricing':'Clear Pricing','market.clearPricingSub':'See the price before opening a listing','market.protected':'Protected Manager','market.protectedSub':'Upload and editing are Admin only','market.browseStore':'BROWSE THE STORE','market.featured':'Featured Prompts','market.featuredDesc':'Choose a prompt product and open it to see more details.','market.collection':'Premium Prompt Collection','market.loading':'Loading prompts...','market.viewPrompt':'View Prompt','market.noPrompts':'No prompts found.','market.loadError':'Could not load prompts.','market.defaultDesc':'Premium PromptStudio prompt','market.promptProduct':'PROMPT PRODUCT','market.buyNow':'Buy Now','market.backHome':'← Back Home','market.controlled':'Marketplace content is controlled by Admin.','market.controlledDesc':'Customer accounts can browse and sign in, while upload/edit/delete permissions remain protected by Supabase roles and RLS.','market.footer':'© 2026 PromptStudio — Premium Video Prompt Marketplace',
      'admin.manager':'Admin Prompt Manager','admin.managerDesc':'Only Admin accounts can upload, edit, or delete marketplace prompt products.','admin.close':'Close Admin Panel','admin.upload':'Upload New Prompt','admin.cover':'Cover Image','admin.choose':'Choose an image','admin.title':'Title','admin.titlePh':'Prompt title','admin.category':'Category / Style','admin.categoryPh':'e.g. Cinematic','admin.price':'Price (USD)','admin.duration':'Duration','admin.short':'Short Description','admin.shortPh':'Short customer-facing description','admin.full':'Full Prompt','admin.fullPh':'Paste the full AI video prompt here...','admin.publish':'Publish Prompt','admin.reset':'Reset','admin.manage':'Manage Prompts','admin.edit':'Edit','admin.delete':'Delete','admin.published':'Published','admin.draft':'Draft','admin.editPrompt':'Edit Prompt','admin.saveChanges':'Save Changes','admin.permission':'Admin permission required.','admin.required':'Title, category and full prompt are required.','admin.saving':'Saving...','admin.saved':'Saved successfully.','admin.saveError':'Could not save prompt.','admin.confirmDelete':'Delete this prompt?','admin.none':'No prompts yet.',
      'auth.login':'Login','auth.signup':'Sign Up','auth.fullName':'Full Name','auth.namePh':'Your name','auth.email':'Email','auth.password':'Password','auth.passwordPh':'At least 6 characters','auth.create':'Create Account','auth.working':'Working...','auth.created':'Account created. Check your email if confirmation is required.','auth.success':'Success.'
    },
    km:{
      'brand.subtitle':'ទីផ្សារ Video Prompt','nav.home':'ទំព័រដើម','nav.browse':'មើល Prompt','nav.explore':'ចូលមើលទីផ្សារ','nav.admin':'ផ្ទាំង Admin','nav.login':'ចូលគណនី','nav.signup':'ចុះឈ្មោះ','nav.logout':'ចាកចេញ',
      'home.badge':'★ VIDEO PROMPT កម្រិត PREMIUM','home.titleA':'បង្កើតវីដេអូស្អាត','home.titleB':'បានលឿនជាងមុន','home.desc':'ស្វែងរក និងទិញ AI Video Prompt គុណភាពខ្ពស់ សម្រាប់គ្រប់ Style, Mood និង Platform។ ចាប់ផ្តើមពីគំនិតដែលរឹងមាំ និងបង្កើតវីដេអូបានលឿន។','home.explore':'ចូលមើលទីផ្សារ →','home.new':'មើល Prompt ថ្មី','home.premium':'គុណភាព Premium','home.premiumSub':'Prompt ដែលបានជ្រើសរើសយ៉ាងល្អ','home.save':'ចំណេញពេលវេលា','home.saveSub':'បង្កើតបានលឿនជាមួយគំនិតរួចរាល់','home.creators':'សម្រាប់ Creator គ្រប់គ្នា','home.creatorsSub':'សមស្របសម្រាប់វីដេអូគ្រប់ Style','home.likes':'ចំនួនអ្នកចូលចិត្ត','home.views':'ចំនួនអ្នកចូលមើល','home.buyers':'ចំនួនអ្នកទិញ','home.made':'បង្កើតសម្រាប់ CREATOR','home.showTitle':'អ្វីៗដែលអ្នកត្រូវការ ដើម្បីបម្លែងគំនិតទៅជាវីដេអូល្អជាងមុន។','home.showDesc':'PromptStudio ផ្តោតលើ Prompt ដែលស្អាត ងាយប្រើ និងមានប្រយោជន៍។ អ្នកអាចមើលគំរូ ប្រៀបធៀបតម្លៃ និងមើលព័ត៌មាន Prompt មុនទិញ។','home.move':'ធ្វើការលឿនជាងមុន','home.moveDesc':'កុំចាប់ផ្តើមពីសូន្យ។ ប្រើ Prompt ដែលមានរចនាសម្ព័ន្ធសម្រាប់ Video Generation។','home.presentation':'ការបង្ហាញ Premium','home.presentationDesc':'គ្រប់ Listing មាន Cover, ចំណងជើង, Category, Duration, Description និងតម្លៃច្បាស់។','home.easy':'ទីផ្សារងាយប្រើ','home.easyDesc':'មើលហាងបានស្រួល ខណៈសិទ្ធិ Admin ត្រូវបានការពារនៅ Backend។','home.marketKicker':'ទីផ្សារ PROMPT','home.marketTitle':'ហាងស្អាតសម្រាប់ Prompt កម្រិត Premium។','home.marketDesc':'មើលផលិតផលជាមួយរូប Preview ធំៗ តម្លៃច្បាស់ និងបទពិសោធន៍ទិញងាយស្រួល។','home.openBrowse':'បើកទំព័រ Prompt','home.ready':'ត្រៀមបង្កើតហើយឬនៅ?','home.finalTitle':'ស្វែងរក Video Prompt សម្រាប់គម្រោងបន្ទាប់របស់អ្នក។','home.finalDesc':'ចូលទៅកាន់ Marketplace ហើយជ្រើស Prompt ដែលសមនឹងគម្រោងរបស់អ្នក។','home.browseArrow':'មើល Prompt →','home.footer':'© 2026 PromptStudio — ទីផ្សារ Video Prompt Premium',
      'market.badge':'✦ ទីផ្សារ PROMPTSTUDIO','market.titleA':'ទិញ','market.titleB':'Video Prompt Premium','market.titleC':'សម្រាប់គម្រោងបន្ទាប់របស់អ្នក។','market.desc':'ស្វែងរក Prompt ដែល Admin បានជ្រើសរើស មាន Cover ស្អាត តម្លៃច្បាស់ និងការណែនាំរួចរាល់សម្រាប់ការបង្កើត។','market.searchPlaceholder':'ស្វែងរកតាមចំណងជើង Style ឬ Keyword...','market.search':'ស្វែងរក','market.adminCurated':'Admin ជ្រើសរើស','market.adminCuratedSub':'មានតែ Prompt ដែលបានអនុម័តទើបបង្ហាញ','market.visualListings':'Listing មានរូបភាព','market.visualListingsSub':'មាន Cover ចំណងជើង និងព័ត៌មានលម្អិត','market.clearPricing':'តម្លៃច្បាស់','market.clearPricingSub':'មើលតម្លៃបានមុនបើក Listing','market.protected':'ការពារការគ្រប់គ្រង','market.protectedSub':'មានតែ Admin អាច Upload និងកែបាន','market.browseStore':'មើលហាង','market.featured':'Prompt ពេញនិយម','market.featuredDesc':'ជ្រើស Prompt ហើយបើកមើលព័ត៌មានលម្អិត។','market.collection':'បណ្ណាល័យ Prompt Premium','market.loading':'កំពុងផ្ទុក Prompt...','market.viewPrompt':'មើល Prompt','market.noPrompts':'រកមិនឃើញ Prompt ទេ។','market.loadError':'មិនអាចផ្ទុក Prompt បាន។','market.defaultDesc':'Prompt Premium ពី PromptStudio','market.promptProduct':'ផលិតផល PROMPT','market.buyNow':'ទិញឥឡូវ','market.backHome':'← ត្រឡប់ទៅទំព័រដើម','market.controlled':'មាតិកា Marketplace គ្រប់គ្រងដោយ Admin។','market.controlledDesc':'អតិថិជនអាចមើល និងចូលគណនីបាន ប៉ុន្តែសិទ្ធិ Upload/Edit/Delete ត្រូវបានការពារដោយ Role និង RLS។','market.footer':'© 2026 PromptStudio — ទីផ្សារ Video Prompt Premium',
      'admin.manager':'គ្រប់គ្រង Prompt សម្រាប់ Admin','admin.managerDesc':'មានតែ Admin ប៉ុណ្ណោះដែលអាច Upload កែ ឬលុប Prompt។','admin.close':'បិទ Admin Panel','admin.upload':'បង្ហោះ Prompt ថ្មី','admin.cover':'រូប Cover','admin.choose':'ជ្រើសរើសរូបភាព','admin.title':'ចំណងជើង','admin.titlePh':'ចំណងជើង Prompt','admin.category':'ប្រភេទ / Style','admin.categoryPh':'ឧ. Cinematic','admin.price':'តម្លៃ (USD)','admin.duration':'រយៈពេល','admin.short':'ការពិពណ៌នាខ្លី','admin.shortPh':'ការពិពណ៌នាខ្លីសម្រាប់អតិថិជន','admin.full':'Prompt ពេញ','admin.fullPh':'ដាក់ AI Video Prompt ពេញនៅទីនេះ...','admin.publish':'បង្ហោះ Prompt','admin.reset':'កំណត់ឡើងវិញ','admin.manage':'គ្រប់គ្រង Prompt','admin.edit':'កែ','admin.delete':'លុប','admin.published':'បានបង្ហោះ','admin.draft':'ព្រាង','admin.editPrompt':'កែ Prompt','admin.saveChanges':'រក្សាទុកការកែ','admin.permission':'ត្រូវការសិទ្ធិ Admin។','admin.required':'ត្រូវបំពេញចំណងជើង ប្រភេទ និង Prompt ពេញ។','admin.saving':'កំពុងរក្សាទុក...','admin.saved':'រក្សាទុករួចរាល់។','admin.saveError':'មិនអាចរក្សាទុក Prompt បាន។','admin.confirmDelete':'លុប Prompt នេះមែនទេ?','admin.none':'មិនទាន់មាន Prompt ទេ។',
      'auth.login':'ចូលគណនី','auth.signup':'ចុះឈ្មោះ','auth.fullName':'ឈ្មោះពេញ','auth.namePh':'ឈ្មោះរបស់អ្នក','auth.email':'អ៊ីមែល','auth.password':'ពាក្យសម្ងាត់','auth.passwordPh':'យ៉ាងតិច 6 តួអក្សរ','auth.create':'បង្កើតគណនី','auth.working':'កំពុងដំណើរការ...','auth.created':'បានបង្កើតគណនី។ សូមពិនិត្យអ៊ីមែល ប្រសិនបើត្រូវបញ្ជាក់។','auth.success':'ជោគជ័យ។'
    },
    zh:{
      'brand.subtitle':'视频提示词市场','nav.home':'首页','nav.browse':'浏览提示词','nav.explore':'进入市场','nav.admin':'管理员面板','nav.login':'登录','nav.signup':'注册','nav.logout':'退出登录',
      'home.badge':'★ 高级视频提示词','home.titleA':'更快创作','home.titleB':'惊艳视频','home.desc':'发现并购买适用于各种风格、氛围和平台的高质量 AI 视频提示词。用更好的创意起步，更快完成精美视频。','home.explore':'进入市场 →','home.new':'浏览最新提示词','home.premium':'高级品质','home.premiumSub':'精心筛选的优质提示词','home.save':'节省时间','home.saveSub':'使用现成创意更快创作','home.creators':'适合所有创作者','home.creatorsSub':'支持多种视频风格','home.likes':'社区点赞','home.views':'市场浏览量','home.buyers':'购买用户','home.made':'为创作者打造','home.showTitle':'把创意变成更优秀视频所需的一切。','home.showDesc':'PromptStudio 专注于简洁、实用的提示词产品。查看视觉示例、比较价格，并在购买前了解提示词详情。','home.move':'创作更快','home.moveDesc':'无需从空白开始，直接使用为视频生成设计的结构化提示词。','home.presentation':'高级展示','home.presentationDesc':'每个商品都包含封面、标题、分类、时长、描述和清晰价格。','home.easy':'简洁市场','home.easyDesc':'轻松浏览商店，同时管理员权限在后台得到保护。','home.marketKicker':'提示词市场','home.marketTitle':'一个简洁的高级提示词商店。','home.marketDesc':'大图预览、清晰价格和专注的购物体验。','home.openBrowse':'打开提示词商店','home.ready':'准备开始创作？','home.finalTitle':'今天就找到你的下一个视频提示词。','home.finalDesc':'进入市场，选择适合你下一个项目的提示词。','home.browseArrow':'浏览提示词 →','home.footer':'© 2026 PromptStudio — 高级视频提示词市场',
      'market.badge':'✦ PROMPTSTUDIO 市场','market.titleA':'购买高级','market.titleB':'视频提示词','market.titleC':'开启你的下一次创作。','market.desc':'探索由管理员精选的提示词商品，包含视觉封面、清晰价格和可直接使用的创作方向。','market.searchPlaceholder':'按标题、风格或关键词搜索提示词...','market.search':'搜索','market.adminCurated':'管理员精选','market.adminCuratedSub':'仅发布已审核的提示词','market.visualListings':'视觉商品','market.visualListingsSub':'封面、标题和详细信息','market.clearPricing':'价格清晰','market.clearPricingSub':'打开商品前即可查看价格','market.protected':'安全管理','market.protectedSub':'仅管理员可上传和编辑','market.browseStore':'浏览商店','market.featured':'精选提示词','market.featuredDesc':'选择提示词商品并打开查看更多详情。','market.collection':'高级提示词合集','market.loading':'正在加载提示词...','market.viewPrompt':'查看提示词','market.noPrompts':'未找到提示词。','market.loadError':'无法加载提示词。','market.defaultDesc':'PromptStudio 高级提示词','market.promptProduct':'提示词商品','market.buyNow':'立即购买','market.backHome':'← 返回首页','market.controlled':'市场内容由管理员管理。','market.controlledDesc':'普通用户可以浏览和登录，但上传、编辑和删除权限由 Supabase Role 与 RLS 保护。','market.footer':'© 2026 PromptStudio — 高级视频提示词市场',
      'admin.manager':'管理员提示词管理','admin.managerDesc':'只有管理员账号可以上传、编辑或删除市场提示词。','admin.close':'关闭管理员面板','admin.upload':'上传新提示词','admin.cover':'封面图片','admin.choose':'选择图片','admin.title':'标题','admin.titlePh':'提示词标题','admin.category':'分类 / 风格','admin.categoryPh':'例如 Cinematic','admin.price':'价格 (USD)','admin.duration':'时长','admin.short':'简短描述','admin.shortPh':'面向客户的简短描述','admin.full':'完整提示词','admin.fullPh':'在这里粘贴完整的 AI 视频提示词...','admin.publish':'发布提示词','admin.reset':'重置','admin.manage':'管理提示词','admin.edit':'编辑','admin.delete':'删除','admin.published':'已发布','admin.draft':'草稿','admin.editPrompt':'编辑提示词','admin.saveChanges':'保存更改','admin.permission':'需要管理员权限。','admin.required':'标题、分类和完整提示词为必填项。','admin.saving':'正在保存...','admin.saved':'保存成功。','admin.saveError':'无法保存提示词。','admin.confirmDelete':'确定删除这个提示词吗？','admin.none':'暂无提示词。',
      'auth.login':'登录','auth.signup':'注册','auth.fullName':'姓名','auth.namePh':'你的姓名','auth.email':'邮箱','auth.password':'密码','auth.passwordPh':'至少 6 个字符','auth.create':'创建账号','auth.working':'处理中...','auth.created':'账号已创建。如需验证，请检查邮箱。','auth.success':'成功。'
    }
  };
  const supported=['en','km','zh'];
  let language=localStorage.getItem('promptstudio_language')||'en';
  if(!supported.includes(language))language='en';
  const t=(key)=>dictionaries[language]?.[key]||dictionaries.en[key]||key;
  function apply(){
    document.documentElement.lang=language==='km'?'km':language==='zh'?'zh-CN':'en';
    document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n)});
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{el.placeholder=t(el.dataset.i18nPlaceholder)});
    document.querySelectorAll('[data-lang]').forEach(el=>el.classList.toggle('active',el.dataset.lang===language));
    window.dispatchEvent(new CustomEvent('promptstudio:languagechange',{detail:{language}}));
  }
  function setLanguage(next){if(!supported.includes(next))return;language=next;localStorage.setItem('promptstudio_language',language);apply();}
  function init(){document.querySelectorAll('[data-lang]').forEach(btn=>btn.addEventListener('click',()=>setLanguage(btn.dataset.lang)));apply();}
  window.PromptI18n={t,setLanguage,apply,get language(){return language;}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();