const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const menuBtn=q('#mobileBtn'),menu=q('#menu');if(menuBtn&&menu){menuBtn.addEventListener('click',()=>menu.classList.toggle('open'));qa('#menu a').forEach(a=>a.addEventListener('click',()=>menu.classList.remove('open')))}
qa('.faq-q').forEach(btn=>btn.addEventListener('click',()=>btn.closest('.faq-item')?.classList.toggle('open')));
const promptModal=q('#promptModal'),promptClose=q('#promptClose');function closePrompt(){promptModal?.classList.remove('open');document.body.style.overflow=''}
qa('.prompt-card').forEach(card=>card.addEventListener('click',()=>{if(!promptModal)return;const img=card.dataset.image||'';const title=card.dataset.title||'Prompt';const category=card.dataset.category||'PROMPT';const text=card.dataset.prompt||'Prompt content will be added here.';q('#modalImg').src=img;q('#modalImg').style.display=img?'block':'none';q('#modalCategory').textContent=category.toUpperCase();q('#modalTitle').textContent=title;q('#modalPrompt').textContent=text;promptModal.classList.add('open');document.body.style.overflow='hidden'}));promptClose?.addEventListener('click',closePrompt);promptModal?.addEventListener('click',e=>{if(e.target===promptModal)closePrompt()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closePrompt()});
qa('.filter-chip').forEach(btn=>btn.addEventListener('click',()=>{qa('.filter-chip').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;qa('.prompt-card').forEach(c=>c.style.display=(f==='all'||c.dataset.category===f)?'block':'none')}));
const SUPABASE_URL='https://vlnhsdsncqcugfpjjlas.supabase.co';const SUPABASE_KEY='sb_publishable_S-YSKMI32JyEoPb1cMJL_Q_1_0jKBn0';let sb=null;if(window.supabase){sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})}
function setMsg(text,type=''){const el=q('#authMsg');if(!el)return;el.textContent=text;el.className='auth-msg show '+type}
async function googleLogin(){if(!sb)return;const {error}=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:'https://lensbykai-bit.github.io/NexoraDIGI/learn.html'}});if(error)setMsg(error.message,'error')}
q('#googleLogin')?.addEventListener('click',googleLogin);
q('#emailLoginForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!sb)return;setMsg('Signing in…');const email=q('#loginEmail').value.trim(),password=q('#loginPassword').value;const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)return setMsg(error.message,'error');setMsg('Signed in successfully.','success');renderPortal(data.session)});
q('#emailSignupForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!sb)return;setMsg('Creating account…');const name=q('#signupName').value.trim(),email=q('#signupEmail').value.trim(),password=q('#signupPassword').value;const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)return setMsg(error.message,'error');if(data.session){setMsg('Account created.','success');renderPortal(data.session)}else setMsg('Account created. Check your email to confirm.','success')});
q('#showSignup')?.addEventListener('click',()=>{q('#loginBlock').hidden=true;q('#signupBlock').hidden=false});q('#showLogin')?.addEventListener('click',()=>{q('#signupBlock').hidden=true;q('#loginBlock').hidden=false});
q('#logoutBtn')?.addEventListener('click',async()=>{await sb?.auth.signOut();location.reload()});
async function loadPurchases(user){const list=q('#purchaseList'),count=q('#purchaseCount');if(!list||!sb)return;const {data,error}=await sb.from('purchases').select('id,purchased_at,products(title,category,slug)').eq('user_id',user.id).order('purchased_at',{ascending:false});if(error){list.innerHTML='<div class="purchase-item">Could not load purchases.</div>';return}const rows=data||[];if(count)count.textContent=rows.length;list.innerHTML=rows.length?rows.map(r=>`<div class="purchase-item"><span><b>${r.products?.title||'Prompt'}</b><br><small>${r.products?.category||'PROMPT'}</small></span><a href="buy-prompt.html#${r.products?.slug||''}">Open →</a></div>`).join(''):'<div class="purchase-item">No purchases yet.</div>'}
function loadNotes(){const list=q('#noteList');if(!list)return;const notes=JSON.parse(localStorage.getItem('nexora-notes')||'[]');list.innerHTML=notes.length?notes.map(n=>`<div class="note-item">${escapeHtml(n)}</div>`).join(''):'<div class="note-item">No notes yet.</div>'}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
q('#saveNote')?.addEventListener('click',()=>{const ta=q('#noteText');if(!ta||!ta.value.trim())return;const notes=JSON.parse(localStorage.getItem('nexora-notes')||'[]');notes.unshift(ta.value.trim());localStorage.setItem('nexora-notes',JSON.stringify(notes.slice(0,50)));ta.value='';loadNotes()});
async function renderPortal(session){const user=session?.user;if(!user)return;const auth=q('#authArea'),portal=q('#portal');if(auth)auth.style.display='none';if(portal)portal.classList.add('show');const name=user.user_metadata?.full_name||user.user_metadata?.name||user.email?.split('@')[0]||'Student';q('#studentName')&&(q('#studentName').textContent=name);q('#studentEmail')&&(q('#studentEmail').textContent=user.email||'');await loadPurchases(user);loadNotes()}
(async()=>{if(!sb)return;const {data}=await sb.auth.getSession();if(data.session)renderPortal(data.session);sb.auth.onAuthStateChange((_e,s)=>{if(s)renderPortal(s)})})();
